Update pre-commit.yml

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -20,9 +20,12 @@ jobs:
       run: ./.github/scripts/commit-msg.sh $GITHUB_EVENT_PATH
       continue-on-error: true  # Continue to the next step even if the script fails
 
-    - name: Revert Changes if No Jira Ticket Reference
-      if: failure()
+    - name: Check Commit Message and Revert Changes if Necessary
+      if: always()
       run: |
-        git reset --hard HEAD^
-        exit 1  # Exit with non-zero status code to indicate failure
-
+        COMMIT_MSG=$(git log -1 --pretty=format:%s $GITHUB_SHA)
+        if [[ ! $COMMIT_MSG =~ "HECO-" ]]; then
+          git reset --hard HEAD^
+          echo "Changes reverted as commit message lacks a Jira ticket reference."
+          exit 1  # Exit with non-zero status code to indicate failure
+        fi
